In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("VS Code + Miniconda is working!")

print("I am ready to learn Data Scienc!")

VS Code + Miniconda is working!
I am ready to learn Data Scienc!

# 1. HELLO WORLD

In [3]:
print("HELLO WORLD")

HELLO WORLD

In [4]:
# PRINT NAME
type("HELLO WORLD")

str

In [5]:
print("Hello world".upper())
print("Hello world".lower())
print("Hello world".title())

HELLO WORLD
hello world
Hello World

In [6]:
"Hellllo world".count('l')
"Hellllo world".replace('l','u')

'Heuuuuo worud'

# 2. VARIABLES

In [7]:
msg_1= "I AM LEARNING PYTHON"
msg_1

'I AM LEARNING PYTHON'

In [8]:

456

456

In [9]:
msg_2 = "and its fun!"
msg_2

'and its fun!'

In [10]:
msg_3 = msg_1 + " " + msg_2
f'{msg_3}'
f'{msg_1} abc {msg_2}'

'I AM LEARNING PYTHON abc and its fun!'

# 3. LIST

In [11]:
countries = ["INDIA", 'CHINA' , 'UNITED STATES', 'Brazil']

countries[-1] # negative index denote index starting from end
countries

['INDIA', 'CHINA', 'UNITED STATES', 'Brazil']

In [12]:
countries[2:3] # excludes last index

['UNITED STATES']

### 3.1 ADDING ELEMENTS TO A LIST

In [13]:
countries.append('CANADA')
countries

['INDIA', 'CHINA', 'UNITED STATES', 'Brazil', 'CANADA']

In [14]:
# countries.insert(0,'SPAIN')
# countries.remove('Spain')
# countries.pop(0) ## delete at a particular index
# countries
countries.insert(1,'INDIA')
countries

['INDIA', 'INDIA', 'CHINA', 'UNITED STATES', 'Brazil', 'CANADA']

In [15]:
countries_2=['GERMANY' , 'POLAND', 'UKRAINE']
countries  + countries_2 # concate the two lists

['INDIA',
 'INDIA',
 'CHINA',
 'UNITED STATES',
 'Brazil',
 'CANADA',
 'GERMANY',
 'POLAND',
 'UKRAINE']

In [16]:
nested_list= [countries, countries_2]
nested_list

[['INDIA', 'INDIA', 'CHINA', 'UNITED STATES', 'Brazil', 'CANADA'],
 ['GERMANY', 'POLAND', 'UKRAINE']]

### 3.2 SORTING A LIST

In [17]:
numbers= [4,3,5,7,1,2]
numbers.sort() # increasing order
numbers

[1, 2, 3, 4, 5, 7]

In [18]:
# numbers= [4,3,5,7,1,2]
# numbers.sort(reverse= True) # decreasing order
# numbers
numbers.sort()
numbers

[1, 2, 3, 4, 5, 7]

### 3.3 UPDATE AN ELEMENT

In [19]:
numbers[0]=1000
numbers

[1000, 2, 3, 4, 5, 7]

### 3.4 COPYING A LIST

In [20]:

new_list= countries[:]
new_list
new_list_2= countries.copy()
new_list_2

['INDIA', 'INDIA', 'CHINA', 'UNITED STATES', 'Brazil', 'CANADA']

# 4.DICTIONARY

In [21]:
my_dict = {'key1': 'value1' , 'key2':'value2'}
my_data = {'Name':'Frank' , 'Age':23}

In [22]:
my_data
my_data.values()

dict_values(['Frank', 23])

In [23]:
my_data.keys()

dict_keys(['Name', 'Age'])

In [24]:
my_data.values()

dict_values(['Frank', 23])

In [25]:

my_data['Height']= 1.6
my_data

{'Name': 'Frank', 'Age': 23, 'Height': 1.6}

In [26]:
my_data.update({'Height':1.8})
my_data

{'Name': 'Frank', 'Age': 23, 'Height': 1.8}

### 4.1 COPY OF A DICTIONARY

In [27]:
new_dict = my_data.copy()
new_dict

{'Name': 'Frank', 'Age': 23, 'Height': 1.8}

In [28]:
my_data.pop('Name')
my_data

{'Age': 23, 'Height': 1.8}

In [29]:
del my_data['Age']

my_data

{'Height': 1.8}

In [30]:
my_data.clear()
my_data

{}

# 5.IF STATEMENT

In [31]:
var_1= 5
var_2= 6
if(var_1==var_2):
    print('Equal')
else:
    print('Not equal')

Not equal

# 6.For loop

In [32]:
for i in countries:
    print(i)

INDIA
INDIA
CHINA
UNITED STATES
Brazil
CANADA

In [33]:
for index , country in enumerate(countries , start=1):
    print(index, country)

1 INDIA
2 INDIA
3 CHINA
4 UNITED STATES
5 Brazil
6 CANADA

In [34]:
my_data = {'Name':'Frank' , 'Age':23}

In [35]:
for key,value in my_data.items():
    print(key,value)

Name Frank
Age 23

# 7.FUNCTIONS

In [36]:
def sum_values(a,b):
    x= a+b
    return x

In [37]:
x= sum_values(5,7)
print(x)

12

# 8.BUILT IN FUNCTIONS

In [38]:
len(countries)

6

In [39]:
max([1,2,3,4,6,99,9])
min([1,2,3,4,6,99,9])

1

In [40]:
type(countries)

list

In [41]:
for i in range(1, 100,10):
    print(i)

1
11
21
31
41
51
61
71
81
91

# 9.MODULES

In [42]:
import os
os.getcwd() #Shows current folder
os.listdir() # Lists all files in current folder
os.makedirs("New Fold") #Create a new folder

In [43]:
os.listdir()

['.DS_Store',
 'Exercise_1.ipynb',
 'StudentsPerformance.csv',
 'Python_basics.ipynb',
 'New Fold',
 '.vscode']

# 10. CREATING A DATAFRAME

In [44]:
import pandas as pd

import numpy as np

In [45]:
# creating an array
data = np.array([[1,4],[2,3],[5,6]]) 
data

array([[1, 4],
       [2, 3],
       [5, 6]])

In [46]:
# creating dataframe
df = pd.DataFrame(data, index= ['row1', 'row2' ,'row3'], columns=['col1','col2'])
df

      col1  col2
row1     1     4
row2     2     3
row3     5     6

### 10.1 CREATING DATAFRAME FROM A DICTIONARY

In [47]:
# LISTS USED
states= ['California','New York', 'Texas','Florida']
population = [300000, 400000,500000,600000]

In [48]:
dict_states= {'States':states , 'Population':population}
data_states = pd.DataFrame(dict_states, index= ['Row 1', 'Row 2', 'Row 3','Row 4'])

In [49]:
data_states

           States  Population
Row 1  California      300000
Row 2    New York      400000
Row 3       Texas      500000
Row 4     Florida      600000

### 10.2 CREATING DATAFRAME FROM A csv FILE

In [50]:
df_exam = pd.read_csv('StudentsPerformance.csv')

In [51]:
# show first 5 rows in a dataframe
df_exam.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [52]:
# show all rows
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [53]:
# show last 10 rows in a dataframe
df_exam.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [54]:
df_exam.shape

(1000, 8)

# 11. ATTRIBUTES IN PANDAS

In [55]:
#index attribute
df_exam.index

RangeIndex(start=0, stop=1000, step=1)

In [56]:
# columns attribute
df_exam.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [57]:
# data types of each column
df_exam.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [58]:
df_exam.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# 12. FUNCTIONS IN PANDAS

In [59]:
#no. of rows
len(df_exam)

1000

In [60]:
max(df_exam.index)

999

In [61]:
type(df_exam)

pandas.core.frame.DataFrame

# 13. SELECTING A COLUMN IN DATAFRAME

In [62]:
#select single column
df_exam['math score'].tail()

995    88
996    62
997    59
998    68
999    77
Name: math score, dtype: int64

In [64]:
type(df_exam[['gender','math score']])

pandas.core.frame.DataFrame

### ADDING A NEW COLUMN

In [ ]:
df_exam['language score']=70
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

### ADDING A NEW COLUMN WITH AN ARRAY USING NUMPY

In [66]:
import numpy as np

In [70]:
language_score = np.arange(0,1000)

In [71]:
df_exam['language score'] = language_score
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [ ]:
# create random integers from 1 to 100
int_language_score = np.random.randint(1,100, size=1000)
max(int_language_score)

np.int64(99)

In [74]:
df_exam['language score'] = int_language_score
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,40
1,female,group C,some college,standard,completed,69,90,88,3
2,female,group B,master's degree,standard,none,90,95,93,19
3,male,group A,associate's degree,free/reduced,none,47,57,44,33
4,male,group C,some college,standard,none,76,78,75,39
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,37
996,male,group C,high school,free/reduced,none,62,55,55,74
997,female,group C,high school,free/reduced,completed,59,71,65,23
998,female,group D,some college,standard,completed,68,78,77,63
999,female,group D,some college,free/reduced,none,77,86,86,35

In [75]:
# create random float from 1 to 100
np.random.uniform(1,100, size=1000)

array([17.96150303, 90.83867175, 98.47664505, 44.72224321, 50.96528307,
       71.26517723, 75.37854079, 65.46982085, 33.61749633, 44.84542741,
        6.24089565, 47.72125836,  7.9179055 , 91.70697716,  4.09546071,
       71.15874162, 27.38201481, 46.52253268, 58.53061662, 89.90777264,
        4.15986204, 53.59188333, 57.18710687, 36.02257814, 21.33245047,
       51.89949768, 89.96766268, 67.85689615, 32.16552815, 24.32458575,
       40.90917505, 99.52977632, 71.22492345, 37.78310075, 23.39019743,
       67.65604858, 73.71597937, 80.46502872, 86.57639797, 64.04714928,
        1.05354167, 76.85830391, 25.39546695, 56.10253331, 17.5585155 ,
       37.07881252, 11.65262209, 37.44203072, 21.64908041, 55.52992514,
       90.87671849, 16.75276678, 81.40334908, 98.000609  ,  4.00876268,
       10.58695196, 91.6608603 , 66.54698472,  7.0582061 , 38.78951097,
       87.79246207, 80.36246754, 87.16475162,  4.05686767, 40.30222753,
        9.77105963, 85.56222387, 99.08028213, 98.76981773, 91.26280292,
       69.03196903,  4.39204851, 70.16263926, 76.70478421, 17.02944006,
       48.77432178, 76.80211116,  9.43143108, 81.57538531, 28.34720026,
       14.93755312,  6.02676075, 30.87865169, 33.90102379, 12.03553229,
       42.28918991, 87.57340988, 92.45168246, 43.30550524, 85.59775689,
       26.78442165, 95.69761503, 88.45902915, 12.32763751, 96.63473417,
       16.05356012, 35.96899038, 37.83261366, 17.23813983, 19.30053688,
       21.53585324, 57.69835951, 36.69960369, 78.74224228,  1.95627901,
       76.63908647, 61.90206624, 35.70813977, 44.03778911, 88.16809914,
       47.55780329, 88.69205839, 69.27420561, 91.93040616, 51.41049723,
       42.34714427, 73.27694171, 73.98591924, 87.48925371, 41.2911337 ,
       29.07630181,  2.07539304, 96.43124676, 72.76006558, 50.41673279,
       99.43261851, 98.8985969 , 87.76755448, 71.07438647, 27.22110992,
       22.85151813, 72.52203275, 81.08838488, 44.63883223, 84.60951473,
       70.05785413, 28.95943142, 62.07373388, 24.70058845, 75.45977975,
       81.4449322 , 92.43123779, 67.72421795, 60.24415084, 85.65153069,
       18.77357558, 12.88215622, 84.12254175, 71.62035193, 28.43834005,
       62.38587726, 86.89915199, 44.57835722, 57.5730121 , 85.52099999,
        3.8539994 , 92.39839175, 47.87658608, 26.72045888, 66.45302441,
       97.55979139, 84.9608523 , 65.83950622, 74.34132794, 36.66602824,
       16.13732929, 72.63807649, 57.04460048, 89.97784832, 79.63257039,
       51.17619401, 62.25435577, 70.89549724, 99.63979211, 11.41977075,
       57.36798095, 65.87624004, 13.18814001, 14.6524117 , 73.77954541,
       31.71910879,  2.25529344, 62.96748163, 66.15530127, 26.29600462,
       63.21011627, 91.75845519, 96.05294809, 42.83472751,  2.39554804,
       42.95480596, 22.03001112,  3.8180726 , 19.39578037, 52.32653546,
       18.93171778, 63.61726786, 16.66665063, 56.5442431 , 30.94562829,
       49.03078596, 58.6746818 , 73.78975676, 53.00687129, 14.09337486,
       42.73366543,  5.13597873, 69.09367924, 19.29536648, 39.21730319,
       69.78417156, 54.51103978,  9.95014853,  3.74517221, 55.33502249,
        9.22583905, 16.9485564 , 71.54506244, 73.49114827, 74.41692387,
       59.22274795, 73.60524557, 49.43248298, 68.06436592, 23.19128233,
       51.09960067,  4.44764521, 80.90703869, 86.10795246, 45.05024009,
       83.05605153,  8.10320953, 26.11303719,  1.47589954,  1.42041644,
       65.67747786, 79.16685957,  3.19167666, 80.37377439, 63.68162317,
       53.08204836, 64.75324107,  7.34075509, 20.9581061 , 40.95892853,
       76.701758  , 31.54352964, 94.55663153, 58.98423207, 50.51575748,
       47.37037561, 74.65214247, 19.94770608, 91.98446119, 50.20259313,
       47.98371127, 78.69451335, 25.10433911, 20.4434512 , 41.71525276,
       54.60173689, 15.94886288, 20.03806488, 16.82771936, 18.33986176,
       39.88726094, 32.93140862, 26.91633633, 58.40173617, 64.92667737,
       26.50902663, 57.05775654, 20.66395225, 52.70727721, 68.8806344 ,
       50.52999768, 65.44530681, 57.72050404, 86.13435596, 22.91271463,
       40.55209788, 39.2022184 , 55.49081562, 35.99025359, 56.91849581,
       40.69420649, 31.32622457, 95.52587667, 11.42205982,  9.62102103,
       77.18245449, 56.75600637, 15.30793276, 24.35863118, 96.2965623 ,
       54.41339697, 71.15975828, 67.16192989, 50.05964763, 74.5795198 ,
       85.4260819 , 39.9799722 , 68.42747369, 53.0049816 , 11.47164556,
       29.76725468, 66.4460047 , 38.41615091, 13.19121564, 21.08435064,
       85.17390537, 97.06088638, 97.80572721, 87.46341405, 70.15482131,
       87.71380793, 38.64471886, 50.48349323, 90.4352568 , 68.57413369,
       32.82656057, 34.07122128, 94.73784511, 82.01341955, 32.98019456,
       20.43754559, 73.72651235, 61.2738326 , 27.68650453, 49.50730352,
       49.01578899, 85.57143833, 53.29354486, 13.87734638, 62.77847238,
       31.93616046, 44.95611771, 57.56856296, 82.30971258, 62.47658641,
        8.26629799, 12.99610747,  6.12059541, 68.85916203, 13.22593424,
       79.25171504, 23.51049706, 42.40300942, 70.9683416 , 90.12073321,
       52.76435736, 39.25862296, 44.75417153, 10.50340057, 25.00188653,
       38.07058855, 29.54920943, 49.53090428,  6.59937592, 57.4446539 ,
       65.67488051, 57.17926766, 69.9536908 , 32.07990619, 72.67292107,
       39.96981788, 69.68017513,  1.32991006, 71.29868477, 28.67904689,
        9.59032095,  3.86767286, 74.20148087, 47.71929115, 80.53897974,
       76.10231964, 46.68169747, 42.70437553, 71.9597958 , 10.57349195,
       64.3935474 , 41.49718543, 44.10928703, 43.50431094, 73.60833984,
       32.02217127, 10.338046  , 94.92183847, 65.98004787, 10.7960686 ,
        7.98151398, 98.00619529, 64.00739098, 95.18502252, 33.29347681,
       84.74866822, 76.65066061, 91.67212476, 82.00915985, 61.74280506,
       68.24628949, 39.37498171, 61.33203947, 54.97862914, 99.43000409,
       57.41704521, 15.85847781, 76.85489341, 14.79659089, 43.31293431,
       52.63840031, 88.81691257, 94.84443386, 96.42762189, 89.8927971 ,
       59.08956439, 66.35489807, 27.10362514, 27.54494398,  7.58675259,
       16.57068103,  4.41638777,  7.35578535, 94.04787176, 85.00721895,
       66.53219369, 48.47837641, 75.78842763, 46.32795464, 73.14405817,
       54.56562734, 93.25317234, 69.20202095, 65.9532067 , 54.12455102,
       99.00684574, 15.25435231, 75.58516462, 68.79149769, 56.27044075,
       55.67989487, 81.65055895, 58.54748388, 66.59432124, 78.47502127,
       80.76632394, 37.99796687, 68.79063786, 57.94939355,  4.23834986,
       71.12259566,  3.3397434 , 51.46981436,  2.9571165 ,  7.37386851,
       46.37330125, 51.29748765, 57.39810774, 17.53353443, 29.98903347,
       55.31878535, 90.00760286, 67.42789126, 76.40635508, 60.16566395,
       26.21546606, 78.01479156, 17.4310933 , 37.11768668, 98.47627386,
       24.56613985, 11.54306162, 76.22133541, 36.21570983, 97.04125372,
       86.80222366,  4.12339897,  3.71009696, 13.87226269, 86.63692921,
       32.89980311, 19.30746849,  2.39600366, 65.05621209, 88.80542172,
       51.41649865, 66.41340899, 10.95826692, 51.52357241, 13.50798623,
       68.05673517, 46.27284689, 55.52253902, 40.16140487, 33.70957822,
       53.13606273, 85.81771883, 45.1289623 ,  9.64887281, 26.32043642,
       11.7710044 , 85.07062483, 55.11170666, 30.75376483, 66.77159274,
       74.59995863, 43.00755511, 65.96187865, 74.61886008, 26.08628127,
       31.33846057, 73.22769865, 85.15134499,  1.5335866 , 98.68345467,
       42.82770888, 97.78206495, 13.22654051, 58.97341625, 18.30158279,
       62.75950814, 58.60580145, 79.62769811, 32.31992086, 55.3014165 ,
       25.07056935, 71.4395544 ,  6.44070704, 42.31722603, 15.0038666 ,
       26.68663946, 30.89811965, 55.49290266, 58.99311123, 37.51580273,
       63.40565187,  1.94204029, 34.19761472, 65.50953008, 56.85213885,
       31.24519877, 73.91835963, 65.19453271, 21.70492515, 73.71935382,
        5.21885553, 47.97535739, 78.05591755, 36.33994857, 13.20599627,
       30.92887316, 32.43278612, 25.25057647, 16.98024209, 74.10907807,
       42.90462957, 30.7747323 , 21.62865594, 16.10446084, 90.21671223,
       92.71677084, 18.27912152, 68.63103159, 64.71978298, 20.90570596,
       74.40921494, 11.58510001, 14.17459214, 96.24755358, 43.16045478,
       11.64989351, 13.87184146, 73.64871155, 25.77798242, 58.31849803,
       16.21324363, 89.90447839,  8.23122117, 52.13005493, 20.52974266,
       96.98444685,  3.18621896, 82.14948478, 88.37365084, 90.36579635,
        8.13957118, 74.55700114, 51.06168071, 43.55327868, 68.46829067,
       82.77328609, 69.94015928, 24.13541683, 22.60020846, 24.81034045,
       50.59375902, 40.94687183, 94.12127166, 97.39661709, 44.80823567,
       40.38337563, 99.30005664,  6.16497523, 35.43734113, 12.4046522 ,
       15.23954853, 92.17431039, 22.35863508, 41.42039518, 10.64613722,
       65.74290827, 80.1353253 , 98.37656565, 81.69006922, 82.6288509 ,
       22.51500982, 18.1344481 , 13.9303196 , 68.36821932, 66.52158468,
       43.65186393, 36.34833838, 77.58747222, 63.18303932,  8.87215377,
        4.12720119, 85.22402859, 17.88688248, 74.90301501, 18.31571814,
        4.03452232, 21.05768988, 29.04759249, 74.32159745, 75.1118242 ,
       45.19530975, 55.80100146, 38.47837867, 68.17482744, 46.02813077,
        8.44129588, 53.23444573, 40.46745217, 24.4744602 , 34.60371013,
       94.30557206, 83.77122182, 17.56255592, 29.18154432, 84.6784131 ,
       76.41456981, 97.91156191, 63.6346895 , 22.47972119, 15.73107987,
       83.18378778, 43.31760424, 44.84889095, 36.12666264,  3.00505504,
        6.81682874, 38.27028592, 96.1920526 , 90.2669772 , 45.94599704,
        1.5909811 , 45.16174739, 13.25687741, 65.34381057, 77.39009789,
       50.70460691, 35.18577712, 12.37100812, 37.34855635, 28.27266139,
       80.50545036, 61.48612015, 95.79217936, 89.95928229, 82.338976  ,
       18.03899604, 32.94970308, 74.13051248, 78.39523866,  9.72802873,
        4.77474083, 63.8115526 , 80.58767735,  5.91041561, 86.09984381,
       75.74762635, 81.25527079, 23.6663012 , 60.23071424, 68.27874229,
       33.31016908, 15.242429  , 35.38892542, 25.90658555, 96.29689508,
       79.67377953, 17.2900511 , 70.00400722,  3.60911267, 94.02630384,
       67.21815207,  7.080129  , 53.04873999, 56.03177243, 33.33603229,
       32.94262427, 60.47075457, 65.4258976 , 33.70390224, 13.31347093,
       55.34014218, 53.52550458, 31.30473879,  4.47627266,  4.85856897,
       43.38658267, 64.44415274, 42.95345875,  4.03621962, 35.32570205,
       59.39055057, 83.80595422, 97.7178519 , 85.02435859, 49.69109523,
       72.48904249, 24.88949731, 42.68173096,  5.44683705, 13.4743474 ,
       84.46049688, 31.58335298, 83.87511654, 57.3173335 ,  8.57952236,
       10.26607881, 13.58085543, 67.4519418 , 82.25237671, 57.0839421 ,
       67.39377878, 46.04466835, 10.34482447, 27.44235421, 60.22208499,
       86.64580091, 64.19455843, 83.1781016 , 85.01770158, 62.20142875,
       60.68456008, 24.76399931, 30.61490551, 45.58415838, 16.41155788,
       59.29054275, 21.55450298, 74.39368889, 13.17517268, 14.10129949,
       81.42202111, 79.53595793, 97.22259828, 12.50133962, 33.46926426,
       25.1653422 ,  7.1170105 , 16.48108758,  4.42894338, 95.2363471 ,
       98.39915328, 96.58331797, 64.74497538, 12.84031072, 18.08034845,
       69.62964326, 85.27634935, 87.90109298, 41.80100012, 95.83506526,
       59.38189953, 29.22266524, 98.41066639, 86.68642101,  9.43293101,
       17.41413462, 97.07720272, 66.16160335, 10.69855786, 11.55783161,
       35.13825513, 44.05969311, 39.21669434, 19.86073044, 68.54831054,
       75.33442908, 98.04527867, 37.24088395, 63.2223821 , 89.64949807,
       47.49220598, 43.36500435, 52.82301344, 82.72597004, 54.11091062,
       10.21913985, 54.73939442,  5.80629732, 27.29357129,  8.11675238,
       59.04509322, 95.3431476 , 27.57468494, 89.26097833, 70.16153119,
       71.30103533, 88.16933017, 59.98105813, 78.08157744, 67.1635317 ,
        7.78137171, 40.11363134, 93.26111274, 64.17156268, 79.20672738,
       74.61263072, 76.84378403, 75.17779898, 63.65931996, 10.13161645,
       32.212232  , 12.67535571, 91.47418436,  4.02779721, 92.83284997,
       58.61190832, 73.73874031, 83.78814038, 35.96991702, 60.13354681,
        8.14259899, 31.99508309, 31.00686226, 40.18516865, 82.94211316,
       93.25848008, 41.47491513, 80.2937654 , 42.62915077, 68.00273221,
       53.4725601 , 88.10552048, 57.64779737, 80.68857759, 11.40714486,
       22.23735827, 66.45543367, 27.23424996, 88.88851191, 88.05532411,
       49.29123565, 87.34130199, 69.56828111, 42.38883062, 12.24111631,
       95.64075887, 87.17879977, 94.16021576, 81.06919453, 64.73719178,
        4.54692997, 82.84089525, 90.73941329, 97.34758651, 89.0728312 ,
       62.02678339, 42.42411165, 62.59929764, 56.46819117, 75.22070844,
       26.31468351,  8.37390926, 30.38330585, 87.10151552, 63.32530927,
       68.57931679, 51.54666779, 73.62579867, 37.83790483, 62.18345807,
       73.52085643, 98.59428538,  5.46500263, 66.11960904, 25.89674217,
        9.95514734, 81.83714104, 39.17942863, 29.31705353, 30.14587519,
       89.4823103 , 97.31103955, 44.68567809,  3.77112119, 68.51548856,
       48.36884541,  4.84090592, 22.95797979, 81.63448838,  5.16605228,
       28.20693725, 95.76498292, 67.90949691, 24.16322928, 70.59506688,
       34.84782258, 12.33005551, 96.03592439, 42.09442657, 22.78752337,
       91.21078917, 57.1903007 , 68.46869138, 78.65988566, 99.08899137,
       71.92164123, 82.40594598, 38.93430009, 13.06822571, 59.26007629,
       20.24986881, 10.33528756, 18.67439123, 33.69954817, 63.45882154,
       98.0496775 , 40.54062576, 64.34508393, 60.47221659,  5.8175274 ,
       68.87430153, 60.3484457 , 39.06274638, 14.76039896, 63.73592813,
       97.50451513, 41.12102875,  9.65473629, 70.46480015, 59.26373073,
       90.88367664, 10.89151988, 90.19620737, 86.95794282, 98.4026518 ,
       84.86219065, 52.72662211,  9.59482322, 23.90531983, 58.11268543,
       11.10259331,  3.52827065, 73.32325439, 67.6050379 , 88.83047577,
       84.55928729, 18.47202997, 60.15864176, 85.45638927, 23.99479885,
       44.1698375 , 76.0507232 , 13.9858446 , 16.74411244,  6.97146407,
       24.47260772, 74.48357899, 98.11389706, 78.13927299,  5.42548658,
       75.53038144, 57.6309624 , 37.97664596, 91.7955962 , 10.50283522,
       53.96924463, 44.17663309, 48.46558803, 62.8524482 , 61.79226041,
       33.38167836, 42.57102288, 48.64370451, 96.76310021, 41.89273965])

### ADDING A NEW COLUMN WITH ASSIGN () AND INSERT()

In [ ]:
# create random integers from 1 to 100
score1= np.random.randint(1,100, size= 1000)
score2= np.random.randint(1,100, size= 1000)

In [80]:
# create series using scores
series1= pd.Series(score1, index= np.arange(0,1000))
series2= pd.Series(score2, index= np.arange(0,1000))

In [84]:
# adding two column using assign()
df_exam = df_exam.assign(score1 = series1, score2 = series2)
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,40,53,34
1,female,group C,some college,standard,completed,69,90,88,3,55,7
2,female,group B,master's degree,standard,none,90,95,93,19,35,57
3,male,group A,associate's degree,free/reduced,none,47,57,44,33,44,30
4,male,group C,some college,standard,none,76,78,75,39,66,70
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,37,45,63
996,male,group C,high school,free/reduced,none,62,55,55,74,65,96
997,female,group C,high school,free/reduced,completed,59,71,65,23,10,45
998,female,group D,some college,standard,completed,68,78,77,63,57,66
999,female,group D,some college,free/reduced,none,77,86,86,35,75,21

In [ ]:
df_exam.insert(1,'test', series1)
df_exam

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,53,group B,bachelor's degree,standard,none,72,72,74,40,53,34
1,female,55,group C,some college,standard,completed,69,90,88,3,55,7
2,female,35,group B,master's degree,standard,none,90,95,93,19,35,57
3,male,44,group A,associate's degree,free/reduced,none,47,57,44,33,44,30
4,male,66,group C,some college,standard,none,76,78,75,39,66,70
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,45,group E,master's degree,standard,completed,88,99,95,37,45,63
996,male,65,group C,high school,free/reduced,none,62,55,55,74,65,96
997,female,10,group C,high school,free/reduced,completed,59,71,65,23,10,45
998,female,57,group D,some college,standard,completed,68,78,77,63,57,66
999,female,75,group D,some college,free/reduced,none,77,86,86,35,75,21

# OPERATIONS ON DATAFRAME
## MATH OPERATIONS
### OPERATIONS IN COLUMN

In [86]:
# CALC SUM OF A COLUMN
df_exam['math score'].sum()

np.int64(66089)

In [94]:
#count mean, std , max, min
df_exam['math score'].count()
df_exam['math score'].mean()
df_exam['math score'].max()
df_exam['math score'].std()
df_exam['math score'].describe()

count    1000.00000
mean       66.08900
std        15.16308
min         0.00000
25%        57.00000
50%        66.00000
75%        77.00000
max       100.00000
Name: math score, dtype: float64

### OPERATION IN ROWS

In [98]:
# SUM OF ROWS
total_score = df_exam['math score']  +  df_exam['reading score'] + df_exam['writing score']

In [103]:
# calc mean of rows and store it in a new column
total_avg= total_score/3
df_exam['total_avg']= total_avg
df_exam.round(2)
df_exam

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,total_avg
0,female,53,group B,bachelor's degree,standard,none,72,72,74,40,53,34,72.666667
1,female,55,group C,some college,standard,completed,69,90,88,3,55,7,82.333333
2,female,35,group B,master's degree,standard,none,90,95,93,19,35,57,92.666667
3,male,44,group A,associate's degree,free/reduced,none,47,57,44,33,44,30,49.333333
4,male,66,group C,some college,standard,none,76,78,75,39,66,70,76.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,45,group E,master's degree,standard,completed,88,99,95,37,45,63,94.000000
996,male,65,group C,high school,free/reduced,none,62,55,55,74,65,96,57.333333
997,female,10,group C,high school,free/reduced,completed,59,71,65,23,10,45,65.000000
998,female,57,group D,some college,standard,completed,68,78,77,63,57,66,74.333333
999,female,75,group D,some college,free/reduced,none,77,86,86,35,75,21,83.000000

## VALUE COUNTS METHOD

In [ ]:
# count by category
df_exam['gender'].value_counts()
df_exam['math score'].value_counts()

math score
65    36
62    35
69    32
59    32
73    27
      ..
24     1
26     1
19     1
23     1
8      1
Name: count, Length: 81, dtype: int64

In [109]:
#shows it as a percentage (proportion) instead of raw numbers!
df_exam['gender'].value_counts(normalize= True).round(2)

gender
female    0.52
male      0.48
Name: proportion, dtype: float64

# SORTING A DATAFRAME

In [ ]:
# sort a column
df_exam.sort_values(by='math score') # sort in ascending

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,total_avg
59,female,23,group C,some high school,free/reduced,none,0,17,10,37,23,51,9.000000
980,female,34,group B,high school,free/reduced,none,8,24,23,51,34,94,18.333333
17,female,84,group B,some high school,free/reduced,none,18,32,28,15,84,16,26.000000
787,female,48,group B,some college,standard,none,19,38,32,45,48,97,29.666667
145,female,35,group C,some college,free/reduced,none,22,39,33,43,35,80,31.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,male,38,group A,some college,standard,completed,100,96,86,50,38,38,94.000000
625,male,56,group D,some college,standard,completed,100,97,99,55,56,24,98.666667
962,female,9,group E,associate's degree,standard,none,100,100,100,39,9,7,100.000000
458,female,41,group E,bachelor's degree,standard,none,100,100,100,78,41,69,100.000000
916,male,71,group E,bachelor's degree,standard,completed,100,100,100,58,71,4,100.000000

In [114]:
df_exam.sort_values('math score' , ascending = False) # sort in descending

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,total_avg
451,female,4,group E,some college,standard,none,100,92,97,20,4,89,96.333333
458,female,41,group E,bachelor's degree,standard,none,100,100,100,78,41,69,100.000000
962,female,9,group E,associate's degree,standard,none,100,100,100,39,9,7,100.000000
149,male,12,group E,associate's degree,free/reduced,completed,100,100,93,91,12,48,97.666667
623,male,38,group A,some college,standard,completed,100,96,86,50,38,38,94.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,35,group C,some college,free/reduced,none,22,39,33,43,35,80,31.333333
787,female,48,group B,some college,standard,none,19,38,32,45,48,97,29.666667
17,female,84,group B,some high school,free/reduced,none,18,32,28,15,84,16,26.000000
980,female,34,group B,high school,free/reduced,none,8,24,23,51,34,94,18.333333
59,female,23,group C,some high school,free/reduced,none,0,17,10,37,23,51,9.000000

In [116]:
# sort multiple columns. use square brackets for multiple `columns`
df_exam.sort_values(['math score', 'reading score'])

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,total_avg
59,female,23,group C,some high school,free/reduced,none,0,17,10,37,23,51,9.000000
980,female,34,group B,high school,free/reduced,none,8,24,23,51,34,94,18.333333
17,female,84,group B,some high school,free/reduced,none,18,32,28,15,84,16,26.000000
787,female,48,group B,some college,standard,none,19,38,32,45,48,97,29.666667
145,female,35,group C,some college,free/reduced,none,22,39,33,43,35,80,31.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,male,56,group D,some college,standard,completed,100,97,99,55,56,24,98.666667
149,male,12,group E,associate's degree,free/reduced,completed,100,100,93,91,12,48,97.666667
458,female,41,group E,bachelor's degree,standard,none,100,100,100,78,41,69,100.000000
916,male,71,group E,bachelor's degree,standard,completed,100,100,100,58,71,4,100.000000
962,female,9,group E,associate's degree,standard,none,100,100,100,39,9,7,100.000000

## SORT ASCENDING WITH A KEY FUNCTION

In [117]:
df_exam.sort_values('race/ethnicity' , ascending = True, key = lambda col: col.str.lower())

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,total_avg
778,female,92,group A,some college,standard,completed,72,79,82,18,92,2,77.666667
546,female,4,group A,some high school,standard,completed,92,100,97,83,4,57,96.333333
820,female,7,group A,some high school,standard,completed,85,90,92,79,7,22,89.000000
741,female,52,group A,associate's degree,free/reduced,none,37,57,56,91,52,91,50.000000
305,male,63,group A,some college,standard,none,69,67,69,63,63,92,68.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,male,83,group E,associate's degree,standard,completed,71,74,68,89,83,47,71.000000
293,female,45,group E,bachelor's degree,standard,none,65,73,75,67,45,63,71.000000
289,male,54,group E,some high school,standard,completed,77,76,77,46,54,81,76.666667
206,male,84,group E,bachelor's degree,standard,none,82,62,62,52,84,18,68.666667
499,male,37,group E,some college,standard,none,76,71,72,92,37,44,73.000000

# using lambda : A Lambda is a small anonymous function written in one single line!

In [118]:
# SYNTAX  =  lambda arguments: expression
add = lambda x , y : x+y
print(add(9,10))

19

# set_index() and sort_index method

In [119]:
df_exam = pd.read_csv('StudentsPerformance.csv')
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [120]:
import random

In [150]:
new_index = np.arange(0, 1000)
# [0, 1, 2, 3, ..., 999]

# Step 2: Shuffle them randomly
random.shuffle(new_index)
# [473, 21, 867, 5, ...]

## SET INDEX

In [ ]:
# SET new_index column as index

# Step 3: Add as column
df_exam['new_index'] = new_index

# Step 4: Make it the index
df_exam.set_index('new_index', inplace=True) # inplace = True means that we want to modify the original dataframe instead of creating a new one

# Step 5: Display
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
696,female,group B,bachelor's degree,standard,none,72,72,74
682,female,group C,some college,standard,completed,69,90,88
953,female,group B,master's degree,standard,none,90,95,93
601,male,group A,associate's degree,free/reduced,none,47,57,44
392,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
406,female,group E,master's degree,standard,completed,88,99,95
341,male,group C,high school,free/reduced,none,62,55,55
593,female,group C,high school,free/reduced,completed,59,71,65
253,female,group D,some college,standard,completed,68,78,77
967,female,group D,some college,free/reduced,none,77,86,86

## SORT INDEX METHOD

In [ ]:
df_exam.sort_index(inplace=True) # ascending order
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,female,group C,associate's degree,standard,completed,67,84,81
1,female,group C,associate's degree,standard,completed,52,59,62
2,male,group E,high school,free/reduced,completed,86,81,75
3,male,group B,master's degree,free/reduced,none,49,53,52
4,female,group C,bachelor's degree,free/reduced,completed,66,74,81
...,...,...,...,...,...,...,...,...
995,male,group C,high school,standard,completed,72,67,64
996,female,group E,some college,standard,none,61,64,62
997,male,group C,associate's degree,standard,completed,57,54,56
998,female,group C,high school,free/reduced,none,41,46,43
999,female,group C,some high school,standard,none,77,91,88

In [157]:
# sort descending
df_exam.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,female,group C,some high school,standard,none,77,91,88
998,female,group C,high school,free/reduced,none,41,46,43
997,male,group C,associate's degree,standard,completed,57,54,56
996,female,group E,some college,standard,none,61,64,62
995,male,group C,high school,standard,completed,72,67,64
...,...,...,...,...,...,...,...,...
4,female,group C,bachelor's degree,free/reduced,completed,66,74,81
3,male,group B,master's degree,free/reduced,none,49,53,52
2,male,group E,high school,free/reduced,completed,86,81,75
1,female,group C,associate's degree,standard,completed,52,59,62
0,female,group C,associate's degree,standard,completed,67,84,81

# RENAMING A COLUMN

In [ ]:
df_exam.rename(columns = {'gender' : 'Gender'})
df_exam.rename(columns = {'gender' : 'Gender' , 'reading score':'RS' , 'math score':'MS' , 'writing score':'WS' }, inplace=True) 
df_exam

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS
new_index,,,,,,,,
0,female,group C,associate's degree,standard,completed,67,84,81
1,female,group C,associate's degree,standard,completed,52,59,62
2,male,group E,high school,free/reduced,completed,86,81,75
3,male,group B,master's degree,free/reduced,none,49,53,52
4,female,group C,bachelor's degree,free/reduced,completed,66,74,81
...,...,...,...,...,...,...,...,...
995,male,group C,high school,standard,completed,72,67,64
996,female,group E,some college,standard,none,61,64,62
997,male,group C,associate's degree,standard,completed,57,54,56
998,female,group C,high school,free/reduced,none,41,46,43
999,female,group C,some high school,standard,none,77,91,88

## RENAMING INDEX

In [164]:
df_exam.rename(index={0:'A', 1:'B', 2:'C'} , inplace=True) 
df_exam.head(3)

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS
new_index,,,,,,,,
A,female,group C,associate's degree,standard,completed,67,84,81
B,female,group C,associate's degree,standard,completed,52,59,62
C,male,group E,high school,free/reduced,completed,86,81,75